### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBaseName' of null

### ISSUE THREAD

**Issue by Skyfold** [bali182/autocomplete-json#38]
[Enter steps to reproduce below:]

Just opened a new file, set the file type to JSON and started typing.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-json](https://github.com/bali182/autocomplete-json) package, v1.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBaseName' of null

```
At /Users/SkyFold/.atom/packages/autocomplete-json/dist/root-provider.js:36

TypeError: Cannot read property 'getBaseName' of null
    at RootProvider.getSuggestions (/Users/SkyFold/.atom/packages/autocomplete-json/dist/root-provider.js:36:73)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:29.7.0 editor:indent (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:28.9.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:19.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:10 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:08.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:59.3.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:57.9.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:52.8.0 bracket-matcher:remove-matching-brackets (atom-text-editor.editor.mini.is-focused)
 19x -0:51.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:44.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 grammar-selector:show (atom-text-editor.editor.vim-mode.normal-mode)
     -0:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/SkyFold/git_projects",
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-json, v1.9.0
markdown-preview-plus, v2.2.2
terminal-plus, v0.14.5
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by bali182** [comment]
Thanks for reporting, I'm looking into this :)

**Comment by bali182** [comment]
I could not reproduce this, but I'm on Windows, Atom 1.5.3.

I tried:
- existing json files
- creating json files immediately with a `.json` extension
- creating simple files, then adding the `.json` extension later
- creating files both handled, and not handled by autocomplete-json

Anyways, added extra null checks for stuff that is coming from the atom and autocomplete-plus side, it's up now as v1.9.1. Would you mind updating and trying if the issue still persist?

**Comment by Skyfold** [comment]
Thanks for getting to this so quickly. Using v1.9.1 I don't get the same error.

It may have been because I was editing a json file outside of any project or because of something mac specific.

**Comment by bali182** [comment]
Just out of curiousity, was the json file that produced this error any of the following?

- package.json
- composer.json
- bower.json
- tsconfig.json
.babelrc 

Or something completely unrelated to these, just any regular json file?

**Comment by Skyfold** [comment]
It was untitled. I set the file type with "Grammar Selector: Show". 

Maybe it was not handling empty file names?

**Comment by bali182** [comment]
I think untitled would be fine. But is it possible, that the file was created and not yet saved? In that case I think atom wouldn't be unable to provide a path to the file since it doesn't exist in the file system yet.
