### ISSUE TITLE
Failed to activate the autocomplete-json package

### ISSUE THREAD

**Issue by akrisanov** [bali182/autocomplete-json#48]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-json](https://github.com/bali182/autocomplete-json) package, v1.11.0

### Stack Trace

Failed to activate the autocomplete-json package

```
At Cannot find module 'minimatch'

Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/akrisanov/.atom/packages/autocomplete-json/dist/root-provider.js:7:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/akrisanov/.atom/packages/autocomplete-json/dist/main.js:3:23)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-elixir",
      "go-get",
      "go-config",
      "autocomplete-go"
    ],
    "themes": [
      "one-dark-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-json, v1.11.0
autocomplete-modules, v1.4.1
autocomplete-python, v1.7.3
color-picker, v2.1.1
docblockr, v0.7.3
dracula-theme, v1.2.6
editorconfig, v1.4.1
environment, v1.2.0
iex, v0.9.27
language-docker, v1.1.6
language-elixir, v0.13.0
language-liquid, v0.5.1
language-rust, v0.4.6
language-slim, v0.5.0
linter, v1.11.4
linter-elixirc, v1.1.8
linter-python-pep8, v0.2.0
linter-rubocop, v0.4.7
linter-rust, v0.4.6
merge-conflicts, v1.4.3
minimap, v4.24.2
pigments, v0.27.1
python-indent, v0.4.3
python-tools, v0.6.7
racer, v0.20.0
rails-i18n, v0.1.3
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by bali182** [comment]
Thanks for reporting, will look into this once I get home!

**Comment by bali182** [comment]
Couldn't reproduce, but I'm on windows. It looks like for some reason atom failed to install the npm dependencies for you. 

A workaround would be to uninstall - reinstall the package from the ui, or from the command line:
```
apm unlink autocomplete-json
apm install autocomplete-json
```
