### ISSUE TITLE
Failed to load the autocomplete-json package

### ISSUE THREAD

**Issue by scouten** [bali182/autocomplete-json#51]
Steps to reproduce:

1. Install autocomplete-json
2. Launch Atom 1.8.0 or later. (Did not occur with 1.7.x.)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [autocomplete-json](https://github.com/bali182/autocomplete-json) package, v5.0.2

### Stack Trace

Failed to load the autocomplete-json package

```
At Cannot find module 'util-deprecate'

Error: Cannot find module 'util-deprecate'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/scouten/.atom/packages/autocomplete-json/node_modules/tokenizer2/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:30:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/scouten/.atom/packages/autocomplete-json/node_modules/tokenizer2/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:30:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/scouten/.atom/packages/autocomplete-json/node_modules/tokenizer2/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:47:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/scouten/.atom/packages/autocomplete-json/node_modules/tokenizer2/node_modules/through2/node_modules/readable-stream/transform.js:1:97)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-jshint",
      "bracket-matcher",
      "tree-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/scouten/Projects",
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.11.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.0.2
browser-plus, v0.0.60
bug-report, v0.7.1
cobalt2-syntax, v0.3.0
editorconfig, v1.4.1
file-types, v0.5.1
language-babel, v2.26.3
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-eslint, v7.2.2
linter-jshint, v2.1.0
nuclide, v0.141.0
pigments, v0.29.1
standard-formatter, v2.0.1
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by bali182** [comment]
Unfortunately I don't own a Mac, so I can't test it in the same environment as yours. However, I manage to install flawlessly on Windows with Atom 1.8.0. Would you mind trying to uninstall/reinstall? The message looks like `npm install` failed at some point while this package was installed.

**Comment by scouten** [comment]
Yeah, looks like uninstall / reinstall "fixed" the problem. Sorry for the false alarm.

**Comment by bali182** [comment]
No worries, and thanks for reporting it. Better safe than sorry :)
