### ISSUE TITLE
Uncaught Error: Unknown proxy type: SOCKS5

### ISSUE THREAD

**Issue by dev4mobile** [bali182/autocomplete-json#55]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-json](https://github.com/bali182/autocomplete-json) package, v5.1.0
### Stack Trace

Uncaught Error: Unknown proxy type: SOCKS5

```
At /Users/dev4mobile/.atom/packages/autocomplete-json/node_modules/electron-proxy-agent/index.js:143

Error: Unknown proxy type: SOCKS5
  at onproxy (/Users/dev4mobile/.atom/packages/autocomplete-json/node_modules/electron-proxy-agent/index.js:143:13)
  at CallbacksRegistry.apply (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
  at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:243:28)
  at emitThree (events.js:110:13)
  at EventEmitter.emit (events.js:188:7)

```
### Commands

```
     -0:48.1.0 editor:newline-above (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:47.3.0 core:undo (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:47 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:46.3.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:45.9.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:29.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:28.7.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:28.6.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:28.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:28.2.0 vim-mode:select-a-word (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:28.1.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:23.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:01.3.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:00.6.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-java, v1.2.5 (inactive)
autocomplete-json, v5.1.0 (active)
autocomplete-plus, v2.31.1 (active)
class-complete, v6.2.2 (active)
copy-file-contents, v0.3.0 (inactive)
java-class-complete, v0.0.6 (active)
java-generator, v2.2.0 (inactive)
java-importer, v1.4.1 (active)
language-java, v0.23.0 (active)
nuclide, v0.163.0 (active)
svg-preview, v0.9.0 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by bali182** [comment]
@agaricus Do you have any idea what could have happened? I have no issues since the proxy was introduced.

**Comment by agaricus** [comment]
sorry for the delay. today I will look

**Comment by agaricus** [comment]
@dev4mobile obviously your environment(or ~/.atom/.apmrc) is set SOCKS5 proxy
which is recognized as the default for electron
but the agent is not able to work with SOCKS5 proxy type
and I'm not sure what the fix proxy type (socks5://->socks://) will be the solution, although  npm|socks-proxy-agent support socks5=(
if to fix .apmrc is not possible, then as a workaround I recommend you to install SOCKS5 -> HTTP(S) via DeleGate
@bali182 it's my fault. I was seduced by simple definition the proxy agent. this project is a fork without issued. I'll try to contact holder and to solve this problem

**Comment by bali182** [comment]
Ah cool, thank you @agaricus !
